#pragma once

#define TP_PP_COMMA ,
#define TP_PP_SEMICOLON ;

#define TP_PP_SELF(x) x
#define TP_PP_EMPTY(x)
#define TP_PP_EXPAND(x) x
#define TP_PP_WRAP(x) (x)

#define TP_PP_UNWRAP_IMPL(...) __VA_ARGS__
#define TP_PP_UNWRAP(x) TP_PP_UNWRAP_IMPL x

#define TP_PP_DT_COUNT(N29,N28,N27,N26,N25,N24,N23,N22,N21,N20,\
                       N19,N18,N17,N16,N15,N14,N13,N12,N11,N10,\
                       N09,N08,N07,N06,N05,N04,N03,N02,N01,RET,...) RET

#define TP_PP_COUNT(...) TP_PP_DT_COUNT(__VA_OPT__(__VA_ARGS__,)\
    29,28,27,26,25,24,23,22,21,20,\
    19,18,17,16,15,14,13,12,11,10,\
     9, 8, 7, 6, 5, 4, 3, 2, 1, 0)


#define TP_PP_DT_SECRET_CAT_IMPL(A,B) A##B
#define TP_PP_DT_SECRET_CAT(A,B) TP_PP_DT_SECRET_CAT_IMPL(A,B)

#define TP_PP_DT_CAT_2(A,B)     A##B
#define TP_PP_CAT_0()
#define TP_PP_CAT_1(A)       A
#define TP_PP_CAT_2(A,B)     TP_PP_DT_CAT_2(A,B)
#define TP_PP_CAT_3(A,...)   TP_PP_CAT_2(A,TP_PP_CAT_2(__VA_ARGS__))
#define TP_PP_CAT_4(A,...)   TP_PP_CAT_2(A,TP_PP_CAT_3(__VA_ARGS__))
#define TP_PP_CAT_5(A,...)   TP_PP_CAT_2(A,TP_PP_CAT_4(__VA_ARGS__))
#define TP_PP_CAT_6(A,...)   TP_PP_CAT_2(A,TP_PP_CAT_5(__VA_ARGS__))
#define TP_PP_CAT_7(A,...)   TP_PP_CAT_2(A,TP_PP_CAT_6(__VA_ARGS__))
#define TP_PP_CAT_8(A,...)   TP_PP_CAT_2(A,TP_PP_CAT_7(__VA_ARGS__))
#define TP_PP_CAT_9(A,...)    TP_PP_CAT_2(A,TP_PP_CAT_8(__VA_ARGS__))
#define TP_PP_CAT_10(A,...)   TP_PP_CAT_2(A,TP_PP_CAT_9(__VA_ARGS__))
#define TP_PP_CAT_11(A,...)   TP_PP_CAT_2(A,TP_PP_CAT_10(__VA_ARGS__))
#define TP_PP_CAT_12(A,...)   TP_PP_CAT_2(A,TP_PP_CAT_11(__VA_ARGS__))
#define TP_PP_CAT_13(A,...)   TP_PP_CAT_2(A,TP_PP_CAT_12(__VA_ARGS__))
#define TP_PP_CAT_14(A,...)   TP_PP_CAT_2(A,TP_PP_CAT_13(__VA_ARGS__))
#define TP_PP_CAT_15(A,...)   TP_PP_CAT_2(A,TP_PP_CAT_14(__VA_ARGS__))
#define TP_PP_CAT_16(A,...)   TP_PP_CAT_2(A,TP_PP_CAT_15(__VA_ARGS__))

#define TP_PP_DT_CAT(...) TP_PP_DT_SECRET_CAT(TP_PP_CAT_, TP_PP_COUNT(__VA_ARGS__) )(__VA_ARGS__)
#define TP_PP_CAT(...) TP_PP_DT_CAT(__VA_ARGS__)





#define TP_PP_CALL_1_0( FNC,SEP,END)
#define TP_PP_CALL_1_1( FNC,SEP,END,A)     FNC(A) TP_PP_UNWRAP(END)
#define TP_PP_CALL_1_2( FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_1( FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_3( FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_2( FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_4( FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_3( FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_5( FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_4( FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_6( FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_5( FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_7( FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_6( FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_8( FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_7( FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_9( FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_8( FNC,SEP,END,__VA_ARGS__)

#define TP_PP_CALL_1_10(FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_9( FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_11(FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_10(FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_12(FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_11(FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_13(FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_12(FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_14(FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_13(FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_15(FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_14(FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_16(FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_15(FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_17(FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_16(FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_18(FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_17(FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_19(FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_18(FNC,SEP,END,__VA_ARGS__)

#define TP_PP_CALL_1_20(FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_19( FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_21(FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_20(FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_22(FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_21(FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_23(FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_22(FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_24(FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_23(FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_25(FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_24(FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_26(FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_25(FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_27(FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_26(FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_28(FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_27(FNC,SEP,END,__VA_ARGS__)
#define TP_PP_CALL_1_29(FNC,SEP,END,A,...) FNC(A) TP_PP_UNWRAP(SEP) TP_PP_CALL_1_28(FNC,SEP,END,__VA_ARGS__)



#define TP_PP_DT_CALL_1(FNC,SEP,END,...) TP_PP_CAT_2(TP_PP_CALL_1_, TP_PP_COUNT(__VA_ARGS__) )(FNC,SEP,END __VA_OPT__(,__VA_ARGS__))
#define TP_PP_CALL_1(FNC,...) TP_PP_DT_CALL_1(FNC,TP_PP_WRAP(;),TP_PP_WRAP(;) __VA_OPT__(,__VA_ARGS__))
#define TP_PP_CALL_EXT_1(FNC,SEP,END,...) TP_PP_DT_CALL_1(FNC,SEP,END __VA_OPT__(,__VA_ARGS__))



#define TP_PP_STR_1(A) #A
#define TP_PP_STR(...) TP_PP_CALL_EXT_1(TP_PP_STR_1,TP_PP_WRAP(TP_PP_COMMA),TP_PP_WRAP(),__VA_ARGS__)